# syntax=docker/dockerfile:1.4
ARG PHP_VERSION=8
ARG BASE_IMAGE_REGISTRY=public.ecr.aws
ARG BASE_IMAGE_PATH=docker/library
FROM ${BASE_IMAGE_REGISTRY}/${BASE_IMAGE_PATH}/composer:latest AS composer
FROM php-${PHP_VERSION}-cli-alpine AS builder

FROM ${BASE_IMAGE_REGISTRY}/${BASE_IMAGE_PATH}/php:${PHP_VERSION}-cli-alpine
# Add dependencies for PIE
ENV PHPIZE_DEPS="${PHPIZE_DEPS} autoconf automake build-base gcc git libtool m4 make"
# Copy PIE and Composer binaries
COPY --link --from=ghcr.io/php/pie:bin /pie /usr/bin/pie
COPY --link --from=composer /usr/bin/composer /usr/local/bin/composer
COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/

# Install dependencies
RUN set -eux; \
    apk update && \
    apk add --no-cache \
# Add helper tools for development \
        curl \
        gettext \
        git \
        netcat-openbsd \
        wget \
# Add SSL support \
        ca-certificates \
        gnupg \
        openssl \
# PHP extension dependencies \
        c-ares \
        freetype \
        icu-libs \
        imagemagick \
        imagemagick-libs \
        libavif \
        libcurl \
        libjpeg-turbo \
        libmcrypt \
        libmemcached-libs \
        libpng \
        libwebp \
        libxslt \
        libzip \
        mongo-c-driver \
        msgpack-c \
        musl \
        rabbitmq-c \
        sqlite-libs \
        unixodbc \
        zlib \
    ;

RUN set -eux \
    ; update-ca-certificates \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-igbinary.ini igbinary \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-msgpack.ini msgpack \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-sockets.ini sockets \
    ; cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=\2|g" $PHP_INI_DIR/php.ini \
    ;

RUN docker-php-ext-enable  \
    apcu \
    memcached \
    redis \
    xdebug \
    xhprof \
    ;

WORKDIR /var/www/html
CMD ["php", "-a"]
