# syntax=docker/dockerfile:1.4
ARG PHP_VERSION=8
FROM php-${PHP_VERSION}-cli AS builder

FROM php:${PHP_VERSION}-cli
# Add dependencies for PIE
ENV PHPIZE_DEPS="${PHPIZE_DEPS} autoconf automake build-essential gcc git libtool m4 make"
ENV DEBIAN_FRONTEND=noninteractive
# Copy PIE and Composer binaries
COPY --link --from=ghcr.io/php/pie:bin /pie /usr/bin/pie
COPY --link --from=composer/composer /usr/bin/composer /usr/local/bin/composer
COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/

# Replace http package sources with https
RUN sed -i 's|http://|https://|g' /etc/apt/sources.list.d/* \
    && apt-get clean \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        gnupg \
        openssl \
    && update-ca-certificates

# Install dependencies
RUN set -eux; \
    apt-get clean; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
# Add helper tools for development \
        curl \
        gettext-base \
        locales \
        netcat-traditional \
        wget \
# PHP extension dependencies \
        `apt-cache pkgnames libavif | sort -V | head -1` \
        `apt-cache pkgnames libc-ares | sort -V | head -1` \
        `apt-cache pkgnames libc6 | sort -V | head -1` \
        `apt-cache pkgnames libcurl4 | sort -V | head -1` \
        `apt-cache pkgnames libfreetype | sort -V | head -1` \
        `apt-cache pkgnames libicu | grep -v "java" | sort -V | head -1` \
        `apt-cache pkgnames libjpeg | sort -V | head -1` \
        `apt-cache pkgnames libmagickcore | grep -v "extra\|headers\|config\|dev"` \
        `apt-cache pkgnames libmagickwand | grep -v "extra\|headers\|config\|dev"` \
        `apt-cache pkgnames libmcrypt | sort -V | head -1` \
        `apt-cache pkgnames libmemcache | sort -V | head -1` \
        `apt-cache pkgnames libmongo | sort -V | head -1` \
        `apt-cache pkgnames libmsgpack | sort -V | head -1` \
        `apt-cache pkgnames libpng | sort -V | head -1` \
        `apt-cache pkgnames librabbitmq | sort -V | head -1` \
        `apt-cache pkgnames libsqlite3 | sort -V | head -1` \
        `apt-cache pkgnames libwebp | sort -V | head -1` \
        `apt-cache pkgnames libxsl | grep -v dev | sort -V | head -1` \
        `apt-cache pkgnames libzip | grep -v "java" | sort -V | head -1` \
        `apt-cache pkgnames unixodbc | sort -V | head -1` \
        `apt-cache pkgnames zlib | sort -V | head -1` \
    && \
    apt-get dist-clean;

RUN set -eux \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-igbinary.ini igbinary \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-msgpack.ini msgpack \
    ; cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=\2|g" $PHP_INI_DIR/php.ini \
    ;

WORKDIR /var/www/html
CMD ["php", "-a"]
