# syntax=docker/dockerfile:1
ARG PHP_VERSION=8
ARG PHP_VARIANT=cli
ARG PHP_BASE_VARIANT=cli
ARG BASE_IMAGE_REGISTRY=public.ecr.aws
ARG BASE_IMAGE_PATH=docker/library
FROM ${BASE_IMAGE_REGISTRY}/${BASE_IMAGE_PATH}/composer:latest AS composer
FROM php-${PHP_VERSION}-${PHP_BASE_VARIANT}-alpine AS builder

FROM ${BASE_IMAGE_REGISTRY}/${BASE_IMAGE_PATH}/php:${PHP_VERSION}-${PHP_VARIANT}-alpine AS runtime
# Add dependencies for PIE
ENV PHPIZE_DEPS="${PHPIZE_DEPS} autoconf automake build-base gcc git libtool m4 make"
# Copy PIE and Composer binaries
COPY --link --from=ghcr.io/php/pie:bin /pie /usr/bin/pie
COPY --link --from=composer /usr/bin/composer /usr/local/bin/composer
COPY --link --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --link --from=builder /root/.pie/ /root/.pie/

# Install dependencies
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    set -eux; \
    apk update && \
    apk add --no-cache \
# Add helper tools for development \
        curl \
        gettext \
        git \
        netcat-openbsd \
        wget \
# Add SSL support \
        ca-certificates \
        gnupg \
        openssl \
# PHP extension dependencies \
        c-ares \
        freetype \
        icu-libs \
        imagemagick \
        imagemagick-libs \
        libavif \
        libcurl \
        libjpeg-turbo \
        libmcrypt \
        libmemcached-libs \
        libpng \
        libwebp \
        libxslt \
        libzip \
        mongo-c-driver \
        msgpack-c \
        musl \
        rabbitmq-c \
        sqlite-libs \
        unixodbc \
        zlib \
    ;

RUN set -eux \
    ; update-ca-certificates \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-igbinary.ini igbinary \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-msgpack.ini msgpack \
    ; docker-php-ext-enable --ini-name 0-docker-php-ext-sockets.ini sockets \
    ; cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=\2|g" $PHP_INI_DIR/php.ini

RUN docker-php-ext-enable  \
    apcu \
    memcached \
    redis \
    xdebug \
    xhprof \
    ;

WORKDIR /var/www/html

FROM runtime AS cli
CMD ["php", "-a"]

FROM runtime AS fpm
RUN set -eux \
    ; sed -i "s/;emergency_restart_threshold\s*=\s*.*/emergency_restart_threshold = 10/g" $PHP_INI_DIR/../php-fpm.conf \
    ; sed -i "s/;emergency_restart_interval\s*=\s*.*/emergency_restart_interval = 1m/g" $PHP_INI_DIR/../php-fpm.conf \
    ; sed -i "s/;process_control_timeout\s*=\s*.*/process_control_timeout = 10s/g" $PHP_INI_DIR/../php-fpm.conf \
    ;
CMD ["php-fpm"]

FROM runtime AS zts
CMD ["php", "-a"]
