name: Base Image Builds

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      variant:
        required: true
        type: string
      os:
        required: true
        type: string
      base_image_registry:
        required: false
        type: string
        default: 'docker.io'

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      packages: write
      actions: write
      contents: read
      pull-requests: write
      id-token: write
      attestations: write
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup variants
        id: compute_variants
        run: |
          echo "variant=${{ inputs.variant }}${{ inputs.os != 'debian' && format('-{0}', inputs.os) || '' }}" >> $GITHUB_OUTPUT
      - name: Setup base image path
        id: image_path
        run: |
          if [ "${{ inputs.base_image_registry }}" = "public.ecr.aws" ]; then
            echo "path=docker/library" >> $GITHUB_OUTPUT
          else
            echo "path=library" >> $GITHUB_OUTPUT
          fi
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/cache/php
          tags: |
            type=raw,value=${{ steps.compute_variants.outputs.variant }},prefix=${{ inputs.version }}-,suffix=-prebuild
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v4
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          cleanup: false
          platforms: ${{ steps.qemu.outputs.platforms }}
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build PHP ${{ inputs.version }} ${{ steps.compute_variants.outputs.variant }} (prebuild)
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: builder/${{ inputs.os }}/Dockerfile-build
          build-args: |
            PHP_VERSION=${{ inputs.version }}
            PHP_VARIANT=${{ inputs.variant }}
            BASE_IMAGE_REGISTRY=${{ inputs.base_image_registry }}
            BASE_IMAGE_PATH=${{ steps.image_path.outputs.path }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          pull: ${{ github.event_name == 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          push: true
          cache-from: ${{ github.run_attempt == 1 && format('type=registry,ref=ghcr.io/{0}/cache/php:{1}-{2}', github.repository_owner, inputs.version, steps.compute_variants.outputs.variant) || '' }}
          cache-to: type=registry,mode=max,ref=${{ format('ghcr.io/{0}/cache/php:{1}-{2}', github.repository_owner, inputs.version, steps.compute_variants.outputs.variant) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}